### ISSUE TITLE
Gracefully handle crash_reason because it can't be encoded with Jason

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/logger_json#10]
See https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L285

**Comment by benwilson512** [comment]
aha! Is this the reason that a process crash isn't showing up in my logs?

**Comment by AndrewDryga** [comment]
@benwilson512 I guess yes, but PR to fix this is on the way #11

**Comment by AndrewDryga** [comment]
@benwilson512 1.3 with a fix is released, please tell if you find anything suspicious.
