### ISSUE TITLE
Upgrade to Elixir 1.15 / Release 6.0.0

### ISSUE THREAD

**Issue by yordis** [Nebo15/logger_json#104]
If I am not mistaken, the package should remove the backend and become a formatter

**Comment by AndrewDryga** [comment]
You can try `master` branch, now this package is just a set of formatters.

**Comment by mgiuliano** [comment]
Any idea when version 6 will be available on Hex? Right now the latest is 5.1.4.

**Comment by AndrewDryga** [comment]
@mgiuliano It's pretty much done but I want to run it for a week or two in our production (it's already there) to make sure it's stable for publishing a package and having others use it.

**Comment by AndrewDryga** [comment]
6.0.0-rc.0 is pushed to hex, please open issues if you hit any issues: https://github.com/Nebo15/logger_json/releases/tag/6.0.0-rc.0

**Comment by AndrewDryga** [comment]
6.0.0 is out.
