### ISSUE TITLE
Need support for LoggerFileBackend

### ISSUE THREAD

**Issue by akchaudhary6532** [Nebo15/logger_json#127]
I want to use LoggerFileBackend and LoggerJson together.

But when I plug them together

```
config :logger,
  backends: [{LoggerFileBackend, :info}]


config :logger, :info,
  path: "/app/info.log",
  level: :info,
  format: {LoggerJSON.Formatters.Elastic, :format},
  metadata: :all
  ```
  
  I get an error `function LoggerJSON.Formatters.Elastic.format/4 is undefined or private`

**Comment by AndrewDryga** [comment]
Have you tried https://www.erlang.org/doc/apps/kernel/logger_std_h? `LoggerFileBackend` is a backend implementation that is a legacy way to integrate with Elixir/Erlang logger, you need a library that integrates with the Erlang logger directly.

**Comment by AndrewDryga** [comment]
Feel free to ask any questions here, closing this for now.
