### ISSUE TITLE
Question: are logs sent properly to Stackdriver Logging?

### ISSUE THREAD

**Issue by bjuretic** [Nebo15/logger_json#13]
I am using the current latest code from `master`. Tis is my config:

```elixir
config :logger_json, :backend,
       metadata: :all,
       formatter: LoggerJSON.Formatters.GoogleCloudLogger

config :logger,
       backends: [LoggerJSON],
       level: :info 
```

Logs are sent to Stackdriver Logging, but they are not parsed, they show up as plaintext logs, although they are JSON structured.

(this is how it looks in the console when viewing the logs)
```
2018-10-22 09:57:13.907 CEST
{"application":{"version":"0.5.17","name":"tzdata"},"log":"Tzdata has updated the release from 2018e to 2018f"}
```

Questions:
1. Are you perhaps not using the V2 LogEntry ? Because the JSON looks like the old version and not like the one described on https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry  - and is this maybe the reason why the logs are not parsed?

2. I am using Elixir in K8S, maybe something needs to be activated/enabled somewhere to tell Stackdriver Logging that it is receiving structured and not plaintext logs?

Thanks for the help!

**Comment by AndrewDryga** [comment]
Hello,

Can you please show a screenshot on where do you look where do you look at those logs? I've checked out logs (and we use version from master branch too) and all logs in Stackdriver are structured. No options needs to be enabled, except Kubernetes cluster version may matter (specifically `fluentd` version and configuration may matter, it's created automatically when you create a cluster in GKE).

LogEntry cannot be logged directly, only some fields are allowed (we use most of them): https://cloud.google.com/logging/docs/agent/configuration#special_fields_in_structured_payloads.

**Comment by bjuretic** [comment]
Hey, thanks for the quick reply. Here is the screenshot. Basically all is there, just unparsed.

![logs](https://user-images.githubusercontent.com/8458429/47291177-f72cff00-d602-11e8-8eb5-33a8e8532fc1.png)

K8S version is 1.9.7-gke.6 , are you perhaps using the 1.10.7-gke.6 ?

p.s. Sorry for two identical cases, there are some problems with GitHub whole morning with the Issues.

**Comment by bjuretic** [comment]
I just updated the cluster (and nodes) to latest 1.10.7-gke.6 and it didn't help, same JSON logs show up as above.

**Comment by AndrewDryga** [comment]
@bjuretic everything looks right on the screenshot, Stackdriver does not apply any special formatting to logs. For example, you can click on `sourceAction` to expand it and you would see file, line and module where logging occurred. All metadata which is not supported by Stackdriver would go to `jsonPayload`. If you have `jsonPayload` field, then logs are formatted and sent correctly.

**Comment by bjuretic** [comment]
Ok I think I know what the issue is, although it's pretty weird.

If you go to the page where you see your own logs, do you have some special settings on the right side, click on "View options and then "Modify custom fields".  For example I added `severity, jsonPayload.application.name, jsonPayload.log` and now it is showing the parsed data. It still shows the JSON right of it, but it is better than before.

![logs2](https://user-images.githubusercontent.com/8458429/47292515-84725280-d607-11e8-945c-ff567853fa6c.png)

Can you let me know what do you have in this Modify custom fields dialog as your settings?

**Comment by bjuretic** [comment]
@AndrewDryga Got it, although it's weird that even if you select fields, it still shows JSON (on the right) in the summary line, which is useless. 
Thanks for the help, closing this!

**Comment by AndrewDryga** [comment]
We have `jsonPayload.request_id, jsonPayload.log`. Having not perfect view is ultimate limitation of Stackdriver, unfortunately.

<img width="1377" alt="2018-10-22 15 42 44" src="https://user-images.githubusercontent.com/1877644/47292920-33675c00-d611-11e8-81be-bbbff2af5962.png">

(You don't need to add `severity` there as it's shown by an icon.)
