### ISSUE TITLE
Stackdriver logs do not show

### ISSUE THREAD

**Issue by mynameisrufus** [Nebo15/logger_json#19]
This might not be an issue it could be me doing something incorrectly.

I have the following in `/etc/google-fluentd/config.d/api.conf`:

```
<source>
    @type tail
    format none
    path /opt/api/var/log/*.log*
    pos_file /var/lib/google-fluentd/pos/api.pos
    read_from_head true
    tag structured-log
</source>
```

As per the guide here https://cloud.google.com/logging/docs/agent/configuration

With the following in my application config:

```elixir
config :logger, backends: [LoggerJSON]
config :logger_json, :backend, json_encoder: Jason
```

With this configuration the log message is in `textPayload` as expected however if I change format in the fluentd conf file from `format none` to `format json` the logs never arrive 🤷‍♂️

**Comment by AndrewDryga** [comment]
@mynameisrufus I'm not sure how to configure standalone fluentd worker to integrate with Stackdriver, can only tell that we use `LoggerJSON` in staging and production Kubernetes clusters on GKE and they work without changing any fluentd configuration.

**Comment by mynameisrufus** [comment]
@AndrewDryga thanks for the reply. I'm going to just log text for now as I don't actually structured logs at this stage it was just a nice to have.
