### ISSUE TITLE
Problem with sourcelocation

### ISSUE THREAD

**Issue by PauloDanielCarneiro** [Nebo15/logger_json#23]
For some reason my sourcelocation only point to {"file":"lib/logger_json/plug.ex","line":44,"function":"Elixir.LoggerJSON.Plug.call/2"}

Is there any problem or something?

In my debug that's the value that handle_events receive in logger_json.ex

**Comment by AndrewDryga** [comment]
@PauloDanielCarneiro that's the value Elixir sends to us (and also an actual place where logger call was made), so logger itself can't do much with it.
