### ISSUE TITLE
Use json logging for mix ecto.migrate

### ISSUE THREAD

**Issue by hawksight** [Nebo15/logger_json#29]
I was wondering if anyone else was also using `mix ecto.migrate` within the application to run migrations on the database before starting the application?

Problem is that no matter what I configure, because the application is not loaded up for mix tasks the config.exs I guess it not read and the mix task just logs with default settings (I'm assuming).

I've done some research and this seems to be my issue... but I cannot find a solution out of the issues:
https://github.com/elixir-ecto/ecto/issues/2038
https://github.com/elixir-ecto/ecto/issues/2225

Just want to keep consistent application logs and hoping someone has a pattern in order to get the migration logs into json (preferably using this library).

**Comment by AndrewDryga** [comment]
@hawksight we are using code similar to this one - https://hexdocs.pm/distillery/1.3.4/running-migrations.html#migration-module and start :logger_json manually, which solves the issue. I'm not sure how do you force it's start for mix apps, especially because mix is usually trimmed from releases.

**Comment by AndrewDryga** [comment]
Closing as idle, please message if this question is still valid or if you have a solution (somebody else might get here looking for it).
