### ISSUE TITLE
Value in adding request_path?

### ISSUE THREAD

**Issue by gabrieltaylor** [Nebo15/logger_json#32]
Hi, maintainers!

First of all, thank you for this excellent library ❤️ 💙 💚 

I know we can add our own formatter, but I'm wondering whether others would find value in including the request path as well as the request url. Having the request path can make it easy to exclude health checks and prometheus metrics requests.

Happy to create the PR if you think others would find this change useful.

**Comment by AndrewDryga** [comment]
Hello @gabrieltaylor.

In which formatter you want to have this added? Google Cloud one already has request URL: https://github.com/Nebo15/logger_json/blob/master/lib/logger_json/plug/metadata_formatters/google_cloud_logger.ex#L34

**Comment by gabrieltaylor** [comment]
Sorry I meant request_path. The request_url in k8s includes the IP of the container which can make it difficult to filter on. Filtering on the path is easier.

**Comment by AndrewDryga** [comment]
@gabrieltaylor feel free to send a PR for it :)
