### ISSUE TITLE
How do I use this with azure?

### ISSUE THREAD

**Issue by mrchypark** [Nebo15/logger_json#36]
Thank you for wonderful package!!

but it looks like only support for gcp.

how can I use this with azure?

Thank you. :)

**Comment by AndrewDryga** [comment]
@mrchypark Hello 👋, nothing stops you from using it on any host and cloud platform, it just structures logs in a format that is native for GCP and prints them to stdout. You can change the format by providing a custom formatter. If Azure has some common fields we can include Azure formatter as part of the library.

**Comment by popaaaandrei** [comment]
I propose that we keep this open until we gather the specs for Azure as well.

**Comment by AndrewDryga** [comment]
@popaaaandrei I think if somebody needs an Asure adapter a PR would be welcome (similar to recent one for DataDog), there is no need to collect the specs. The best PR would be some LoggerJSON formatted that the company used locally in production (so it's testes and user friendly on Azure side) and willing to donate to open source.
