### ISSUE TITLE
Crash when logging logs from OTP

### ISSUE THREAD

**Issue by VitorTrin** [Nebo15/logger_json#40]
```
:gen_event handler LoggerJSON installed in Logger terminating
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for &:application_controller.format_log/1 of type Function, Jason.Encoder protocol must always be explicitly implemented. This protocol is implemented for the following type(s): Ecto.Schema.Metadata, Ecto.Association.NotLoaded, BitString, Date, Atom, NaiveDateTime, Map, Decimal, DateTime, Time, Float, List, Any, Integer, Jason.Fragment
```
It appears that OTP logs have functions in their metadata, the beginning of the metadata of the log that caused the crash:

```
%{domain: [:otp],
 error_logger: %{report_cb: &:application_controller.format_log/1,
 tag: :info_report,
 type: :std_info}, ...
```

the environment is elixir 1.10.3 with OTP 23.0.2

**Comment by AndrewDryga** [comment]
@VitorTrin if this is typical behavior to contain functions I guess we should rework how we encode metadata and recursively traverse it, using everything that implements Jason.Encoder behavior as-is, evaluating functions and inspecting rest. PR would be welcome.

**Comment by skeltoac** [comment]
We had a similar crash due to PIDs in the data.
