### ISSUE TITLE
"time" be overwritten by metadata "time" when use Elixir 1.10 with GoogleCloudLoggingFormatter

### ISSUE THREAD

**Issue by w1mvy** [Nebo15/logger_json#49]
First of all, thank you for this library!!

About the title. Elixir 1.10 integrate with Erlang's logger. And Erlang's logger has metadata "time" what has unixtime(microsecond) variable.

https://elixir-lang.org/blog/2020/01/27/elixir-v1-10-0-released/
https://erlang.org/doc/man/logger.html#timestamp-0

> This allows us to provide tighter integration with Erlang/OTP’s new logger
> This means that the logger level, logger metadata, as well as all log messages are now shared between Erlang and Elixir APIs.

google cloud logger formatter merge metadata and logger_json values, So logger_json's "time" be overwritten by metadata "time" value.
Is it the correct behavior?

My understanding that logger_json be expected "time" value is milliseconds.

I confirmed the behavior as below.

### code

https://github.com/w1mvy/logger_json/commit/39395026d75b7f5fe4074d0d0b3eeb16d1faec8d

### Elixir 1.9

```
%{"logging.googleapis.com/sourceLocation" => %{"file" => "/home/w1mvy/ghq/github.com/Nebo15/logger_json/test/unit/logger_json_google_test.exs", "function" => "Elixir.LoggerJSONGoogleTest.test logs binary messages/1", "line" => 59}, "message" => "hello", "severity" => "DEBUG", "time" => "2020-08-05T21:54:34.233Z"}
```

### Elixir 1.10

```
%{"domain" => ["elixir"], "logging.googleapis.com/sourceLocation" => %{"file" => "/home/w1mvy/ghq/github.com/Nebo15/logger_json/test/unit/logger_json_google_test.exs", "function" => "Elixir.LoggerJSONGoogleTest.test logs binary messages/1", "line" => 59}, "message" => "hello", "severity" => "DEBUG", "time" => 1596632018401128}
```

**Comment by w1mvy** [comment]
In my project,  change the order of merge. But, this change may be breaking change for some people who use metadata "message", "time", "severity".

https://github.com/w1mvy/logger_json/commit/dee65e40dff4cbae93d399d5e558fbfbd5c043b1

If this change is no problem, I can create pull request.

**Comment by AndrewDryga** [comment]
I think that change should not be a problem, but maybe a safer move, for now, would be to simply ignore `:time` key in the metadata in GCL logger. This way even if somebody has a hack that uses that "feature" the change still won't break their code.

**Comment by w1mvy** [comment]
@AndrewDryga thanks your comment.

> for now, would be to simply ignore :time key in the metadata in GCL logger.

I created pull request with this change.

https://github.com/Nebo15/logger_json/pull/51
