### ISSUE TITLE
How do we customise metadata sent to GCL?

### ISSUE THREAD

**Issue by te-chris** [Nebo15/logger_json#59]
Hey, first, thanks for making this, it's exactly what I need! I want to send our session id and userid along with our log entries for grouping/analysis later. Is there a way to pass this in when I use the plug?

**Comment by AndrewDryga** [comment]
Hey @te-chris. There are multiple ways to do that, probably the best one is to define your own Plug metadata formatter and extend it the way you need (here is the default one - https://github.com/Nebo15/logger_json/blob/master/lib/logger_json/plug/metadata_formatters/google_cloud_logger.ex).

Alternatively, if you don't need it in the same log entry as default request log coming from plug, you can simply create a small plug that logs that using `Logger.log("Message", user_id: ..., session_id: ...)`.

**Comment by te-chris** [comment]
Was afraid you'd say that hah :) Sounds good, will look into doing it that way. Thanks!
