### ISSUE TITLE
Logs from LoggerJSON.Plug show as "" in Google Cloud Logging

### ISSUE THREAD

**Issue by marceldegraaf** [Nebo15/logger_json#70]
We're using Elixir/Phoenix and LoggerJSON in our Plug pipelines to format log lines for Google Cloud Logging. These log lines used to be shown with proper labels in the GCL summary line, using fields from `httpRequest`:

<img width="1153" alt="20201027133125-zsxruetksy" src="https://user-images.githubusercontent.com/15011/111654421-0979ea00-8809-11eb-8bb7-3df998bb1926.png">

However, today we noticed these logs are no longer shown that way in GCL, instead showing up as an empty string (`""`) with no labels applied:

<img width="724" alt="20210318164455-6n0pz1haa0" src="https://user-images.githubusercontent.com/15011/111654673-4645e100-8809-11eb-87a7-99e8697fafd8.png">

Expanding one of these log lines still shows the required `httpRequest` fields are present, but GCL seems to take the `jsonPayload.message` (which is logged as an empty string in `LoggerJSON.Plug`) and for some reason no longer shows the `httpRequest` labels:

<img width="963" alt="20210318164659-x5uj18ov72" src="https://user-images.githubusercontent.com/15011/111655151-b2284980-8809-11eb-8499-4ff24664ac91.png">

Things I've tried in a fork of LoggerJSON:
- Log `nil` in `LoggerJSON.Plug`, to see if that would make GCL disregard the `jsonPayload.message` and fall back to the properly formatted log line. This doesn't change anything.
- Remove the `message` field from the payload altogether, if it's empty. This makes GCL show the JSON payload as the log line, instead of showing the properly formatted log line.

Is anyone else experiencing these issues, and do you have any idea how these log lines should be formatted to get proper formatting back in GCL?

**Comment by marceldegraaf** [comment]
Update: I've spent the last few hours debugging this, pouring over documentation and trying to add/remove various fields in `LoggerJSON` to see if that helps. No luck so far.

I've opened a support ticket at Google Cloud, to check if this is caused by a recent change on their end. Will update this issue as I learn more.

**Comment by stevencorona** [comment]
Happens for me as well

**Comment by marceldegraaf** [comment]
Google Cloud Support confirmed this was caused by an error in Google Cloud Logging and Google Kubernetes Engine. It seems to have been fixed in the latest GKE updates.
