### ISSUE TITLE
Issue with GCP latest K8s version

### ISSUE THREAD

**Issue by ashish060211** [Nebo15/logger_json#71]
This library with formatter LoggerJSON.Formatters.GoogleCloudLogger is not working in GCP K8s cluster after 7-April GCP K8S update. Latest update is using fluent-bit agent and earlier one was using fluentD.

**Comment by AndrewDryga** [comment]
@ashish060211 what do you mean by "not working"? Logs are not shown at all? They are corrupted? Which k8s version is that? Our logs on GCloud look good to me and I see that indeed cluster is using fluentbit pods in kube-system.
