### ISSUE TITLE
Changelog/migration guide for going from 4.3.0 to 5.0.0

### ISSUE THREAD

**Issue by s3cur3** [Nebo15/logger_json#86]
Hi there! I have an app using `logger_json` 4.3.0, and I was wondering what (if anything) I need to do to upgrade to 5.0.0.

I looked through the [commits](https://github.com/Nebo15/logger_json/commits/5.0.0), but it wasn't clear to me what the breaking changes might be.

Any help would be much appreciated. (And if this is documented elsewhere, I'd be happy to submit a PR to add it to a `CHANGELOG.md` file or something.)

**Comment by AndrewDryga** [comment]
Hello @s3cur3. The only things that changed are the structure of DataDog formatter (to comply better with DataDog spec) and the minimum required Elixir version.

**Comment by AndrewDryga** [comment]
Added to releases: https://github.com/Nebo15/logger_json/releases/tag/5.0.0

**Comment by s3cur3** [comment]
Awesome, thanks so much!
