### ISSUE TITLE
Formatter for ElasticSearch

### ISSUE THREAD

**Issue by Sgiath** [Nebo15/logger_json#89]
Hi, thanks for awesome library - I love using it on all of my projects.

I wolud like to report my Elixir logs to the ElasticSearch which uses "[Elastic Common Schema](https://www.elastic.co/guide/en/ecs/8.3/ecs-field-reference.html)". Would you be open to merge the formatter to this library or should I do my own?

**Comment by AndrewDryga** [comment]
Hello @Sgiath, I think people on ELK stack already use [BasicLogger](https://github.com/Nebo15/logger_json/blob/master/lib/logger_json/formatters/basic_logger.ex) formatter. Would it fit your needs?

**Comment by AndrewDryga** [comment]
I'm closing this for now, feel free to ask any questions here and we can reopen it as needed.

**Comment by bvobart** [comment]
I'm working on an open-source project professionally where we also need support for logging in ECS format. I've implemented it and opened #116 

@AndrewDryga can you reopen this issue?
