### ISSUE TITLE
ExUnit.CaptureLog support for LoggerJSON backend?

### ISSUE THREAD

**Issue by connorlay** [Nebo15/logger_json#9]
First of all, thank you for creating this library! I have a question regarding ExUnit:

[ExUnit.CapureLog](https://hexdocs.pm/ex_unit/ExUnit.CaptureLog.html#content) is a useful feature for capturing log messages produced during test runs so it can be inspected and suppressed from the console output. I have a test suite that takes advantage of this feature. When I switched our Logger back-end to`LoggerJSON`, these log messages started to appear again in the ExUnit console output.

After reviewing the documentation for `ExUnit.CaptureLog` it appears that the following `test_helper.exs` configuration only supports the `:console` back-end:
```elixir
ExUnit.start(capture_log: true)
```

Do you know of a way to accomplish something similar for the `LoggerJSON` backend? If not, what would you recommend I do to suppress these messages from my test suite?

**Comment by AndrewDryga** [comment]
Hello @connorlay,

Is there a reason why do you want to have JSON logs in test environment? We only enable LoggerJSON in production, thus we get nice logs where we need them and they are still readable/testable in test env.

**Comment by connorlay** [comment]
Thank you @AndrewDryga for the quick response!

Configuring the logger back-end per `mix` environment is not something I had considered. Now that I think about it I would much rather have the readable logs in `dev` and `test` mode. If you think it would be valuable, I can open a small PR adding a note to the documentation regarding `ExUnit.CaptureLog` and per-environment back-ends.

**Comment by AndrewDryga** [comment]
@connorlay sure, I'd be happy to merge docs improvements :)

**Comment by connorlay** [comment]
@AndrewDryga sounds good!
